//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VkusPizza.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CashRegister
    {
        public int Id { get; set; }
        public int IdUser { get; set; }
        public System.DateTime Date { get; set; }
        public decimal SartAmount { get; set; }
        public decimal AmountDay { get; set; }
        public decimal FinalAmount { get; set; }
    
        public virtual User User { get; set; }
    }
}
