//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VkusPizza.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistoryEnter
    {
        public int Id { get; set; }
        public System.DateTime EnterDateTime { get; set; }
        public int LoginId { get; set; }
        public bool Status { get; set; }
    
        public virtual User User { get; set; }
    }
}
