//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VkusPizza.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistoryOrders
    {
        public int Id { get; set; }
        public int IdOrder { get; set; }
        public string Status { get; set; }
        public string UserName { get; set; }
        public decimal Price { get; set; }
    
        public virtual Order Order { get; set; }
    }
}
